package JokenpoClientServer.client;

import java.awt.event.KeyEvent;
import java.io.ObjectOutputStream;
import java.net.Socket;

import JokenpoClientServer.util.Mensagem;

/**
 *
 * @author Gustavo Santos <gustavojspro@hotmail.com>
 */

public class Cliente extends javax.swing.JFrame {
    boolean jogando = false;
    boolean jogoAtivado = false;
    boolean escolhaTime = false;
    int tipoDeJogo = 0;
    String time = "";
    private static final long serialVersionUID = 1L;
    private Socket socket;
    private Escuta escuta;
    private ObjectOutputStream out; 

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();

        txtIP = new javax.swing.JTextField();
        txtPorta = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtHistorico = new javax.swing.JTextArea();
        txtEntrada = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jLabel1.setText("IP");
        jLabel2.setText("Porta");
        jLabel3.setText("Usuário");
        txtIP.setText("127.0.0.1");
        txtPorta.setText("9876");
        btnConectar.setText("Conectar");
        btnConectar.setName("btnConectar"); // NOI18N
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuario))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(btnConectar)
                .addGap(156, 156, 156))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConectar)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Servidor", jInternalFrame1);

        jInternalFrame2.setVisible(true);

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        jScrollPane1.setViewportView(txtHistorico);

        txtEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEntradaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(txtEntrada))
                .addContainerGap())
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chat", jInternalFrame2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }

    private void txtEntradaKeyPressed(java.awt.event.KeyEvent evt) {
        Mensagem msg;
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String player = txtEntrada.getText();
            if(jogando == false && jogoAtivado == false && escolhaTime == false){
                msg = new Mensagem(tipoDeJogo, txtUsuario.getText(), player, time);
                try {
                    out.writeObject(msg);
                    if(player.equals("!jogar")){
                        jogoAtivado = true;
                        txtHistorico.append("Bem vindo ao Jokenpo:\nPara jogar com a CPU digite 1\nPara jogar contra outro jogador digite 2\nPara cancelar o jogo digite qualquer outro numero\nDigite sua resposta:\n");
                    }
                    txtEntrada.setText("");
                } catch (Exception e) {
                    System.out.println("Erro: " + e.getMessage());
                }
            }else if(jogoAtivado == true && jogando == false){
                try{
                    tipoDeJogo = Integer.parseInt(player);
                    if(tipoDeJogo == 1 || tipoDeJogo == 2){
                        jogoAtivado = false;
                        escolhaTime = true;
                        txtHistorico.append("Escolha um time, Azul ou Vermelho?\nPara cancelar escreva 'cancelar'\n");
                    }else{
                        jogando = false;
                        jogoAtivado = false;
                    }
                    txtEntrada.setText("");
                }catch (Exception e) {
                    txtHistorico.append("admin > caractere invalido, tente novamente\n");
                }
            }else if(escolhaTime == true){
                player = player.toLowerCase();
                time = player;
                switch(time){
                    case "azul":
                    case "vermelho":
                        jogando = true;
                        escolhaTime = false;
                        txtHistorico.append("Informe sua jogada\n Pedra, Papel ou Tesoura?\n");
                    break;
                    case "cancelar":
                        jogando = false;
                        jogoAtivado = false;
                        escolhaTime = false;
                        tipoDeJogo = 0;
                        time = "";
                        txtHistorico.append("Jogo cancelado!\n");
                    break;
                    default:
                        txtHistorico.append("admin > caractere invalido, tente novamente\n");
                    break;
                }

                txtEntrada.setText("");

            }else{
                player = player.toLowerCase();
                
                switch(player){
                    case "pedra":
                    case "papel":
                    case "tesoura":
                        msg = new Mensagem(tipoDeJogo, txtUsuario.getText(), player, time);
                        try {
                            out.writeObject(msg);
                            tipoDeJogo = 0;
                            txtEntrada.setText("");
                            jogando = false;
                        } catch (Exception e) {
                            System.out.println("Erro: " + e.getMessage());
                        }
                    break;
                    default:
                        txtHistorico.append("admin > caractere invalido, tente novamente\n");
                    break;
                }
            }
        }
    }

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {
        String ip = txtIP.getText();
        int porta = Integer.parseInt( txtPorta.getText() );

        try {
            socket = new Socket(ip, porta);
            out = new ObjectOutputStream( socket.getOutputStream() );
            escuta = new Escuta(socket, txtHistorico);
            escuta.start();
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPorta;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
